[package]
edition = "2021"
name = "holochain_scaffolding_definitions"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
