name: "check-diff"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop, holochain-0.1 ]
  pull_request:
    branches: [ main, develop, holochain-0.1 ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v18
        with:
          install_url: https://releases.nixos.org/nix/nix-2.12.0/install
          extra_nix_config: |
            experimental-features = flakes nix-command

      - uses: cachix/cachix-action@v10
        with:
          name: holochain-ci

      - name: Install
        run: |
          nix-shell . \
            --keep NIX_PATH \
            --pure \
            --run "cargo generate-lockfile --offline"

      - name: Exit if diff
        run: |
          nix-shell . \
            --keep NIX_PATH \
            --pure \
            --run "git diff --exit-code"
